<a href="https://colab.research.google.com/github/Jetpreethi/airflow_data/blob/main/stage3_success.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Load data
df = pd.read_csv("/content/stores_data_set.csv")

# Perform data cleaning
df.drop_duplicates(inplace=True)
df.fillna({"column_name": "default_value"}, inplace=True)

# Save cleaned data
df.to_csv("cleaned_store_data.csv", index=False)

print("Data cleaning complete. Cleaned data saved to 'cleaned_store_data.csv'.")

Data cleaning complete. Cleaned data saved to 'cleaned_store_data.csv'.

In [ ]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.10/dist-packages (9.0.0)

In [ ]:
import pandas as pd

df = pd.read_csv("/content/cleaned_store_data.csv")

In [ ]:
df.head()

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

In [ ]:
import mysql.connector
import sqlalchemy

In [ ]:
client = mysql.connector.connect(host="data2.ctq8cqeeq8hk.ap-south-1.rds.amazonaws.com",user="admin",password="rootpassword",port=3306)

cursor = client.cursor()

cursor.execute("CREATE DATABASE STORES")

In [ ]:
cursor.execute("SHOW DATABASES")

for i in cursor:
  print(i)

('STORE',)
('STORES',)
('information_schema',)
('mysql',)
('performance_schema',)
('sys',)

In [ ]:
engine=sqlalchemy.create_engine('mysql+mysqlconnector://admin:rootpassword@data2.ctq8cqeeq8hk.ap-south-1.rds.amazonaws.com:3306/STORES')

In [ ]:
df.to_sql("cleaned",engine)

45

In [ ]:
client = mysql.connector.connect(host="data2.ctq8cqeeq8hk.ap-south-1.rds.amazonaws.com",user="admin",password="rootpassword",database="STORES")

In [ ]:
my_cursor=client.cursor()

In [ ]:
my_cursor.execute("SELECT * FROM cleaned")

for i in my_cursor.fetchall():
  print(i)

InternalError: Unread result found

In [ ]:
x = engine.connect()

data = pd.read_sql_table("cleaned",con=x)
data

    index  Store Type    Size
0       0      1    A  151315
1       1      2    A  202307
2       2      3    B   37392
3       3      4    A  205863
4       4      5    B   34875
5       5      6    A  202505
6       6      7    B   70713
7       7      8    A  155078
8       8      9    B  125833
9       9     10    B  126512
10     10     11    A  207499
11     11     12    B  112238
12     12     13    A  219622
13     13     14    A  200898
14     14     15    B  123737
15     15     16    B   57197
16     16     17    B   93188
17     17     18    B  120653
18     18     19    A  203819
19     19     20    A  203742
20     20     21    B  140167
21     21     22    B  119557
22     22     23    B  114533
23     23     24    A  203819
24     24     25    B  128107
25     25     26    A  152513
26     26     27    A  204184
27     27     28    A  206302
28     28     29    B   93638
29     29     30    C   42988
30     30     31    A  203750
31     31     32    A  203007
32     32     33    A   39690
33     33     34    A  158114
34     34     35    B  103681
35     35     36    A   39910
36     36     37    C   39910
37     37     38    C   39690
38     38     39    A  184109
39     39     40    A  155083
40     40     41    A  196321
41     41     42    C   39690
42     42     43    C   41062
43     43     44    C   39910
44     44     45    B  118221